### ISSUE TITLE
Error: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by yrgenkuci** [getsanjeev/classifier-fundus-diabetic-retinopathy#9]
Hello, i'm getting the error below when running bloodvessel.py, any solution behind this?

`
Traceback (most recent call last):
  File "bloodvessels.py", line 62, in <module>
    bloodvessel = extract_bv(fundus)
  File "bloodvessels.py", line 25, in extract_bv
    im2, contours, hierarchy = cv2.findContours(f6.copy(),cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
`

**Comment by NerijaK** [comment]
The line should look smth like this (2 arguments, not 3): 
contours, hierarchy = cv2.findContours(f6.copy(),cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
